export function returnHexadecimalFromLanguages(language: string) {
  switch (language) {
    case "JavaScript":
      return "#f1e05a";
    case "TypeScript":
      return "#2b7489";
    case "HTML":
      return "#e34c26";
    case "CSS":
      return "#563d7c";
    case "Shell":
      return "#89e051";
    case "Python":
      return "#3572A5";
    case "C#":
      return "#178600";
    case "Java":
      return "#b07219";
    case "Ruby":
      return "#701516";
    case "Go":
      return "#00ADD8";
    case "C":
      return "#555555";
    case "C++":
      return "#f34b7d";
    case "PHP":
      return "#4F5D95";
    case "Swift":
      return "#ffac45";
    case "Kotlin":
      return "#F18E33";
    case "Rust":
      return "#dea584";
    case "Dart":
      return "#00B4AB";
    case "Elixir":
      return "#6e4a7e";
    case "Erlang":
      return "#A90533";
    case "Haskell":
      return "#5e5086";
    case "Lua":
      return "#000080";
    case "Perl":
      return "#0298c3";
    case "Scala":
      return "#c22d40";
    case "Clojure":
      return "#db5855";
    case "Groovy":
      return "#4298b8";
    case "R":
      return "#198CE7";
    case "Vue":
      return "#2c3e50";
    case "Assembly":
      return "#6E4C13";
    case "Objective-C":
      return "#438eff";
    case "CoffeeScript":
      return "#244776";
    case "TeX":
      return "#3D6117";
    case "OCaml":
      return "#3be133";
    case "Vim script":
      return "#199f4b";
    case "ClojureScript":
      return "#db5855";
    case "CSS":
      return "#563d7c";
    case "SCSS":
      return "#c6538c";
    case "Sass":
      return "#c6538c";
    case "Less":
      return "#1d365d";
    default:
      return "#000000";
  }
}
